services:
  - type: web
    name: pigfarm-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      cd client && npm install && npx vite build
      cd ../server && npm install && npx shx rm -rf public && npx shx cp -r ../client/dist public/ && tsc
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_WEBHOOK_URL
        sync: false